sudo: required

language: python

python:
  - 2.7
  # for some reason, tests on 3.6 (but not 3.5) seem to run out of memory here but do work fine locally -- not sure what the issue is
  - 3.5

services:
  - docker

before_install:
  - script/up

script:
  - script/test

jobs:
  include:
    - stage: distribute
      if: branch = master AND type != pull_request
      install: skip
      script:
       - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
       - script/distribute-docker
       - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then script/distribute-pypi; fi
