version: '3'
services:
  tf-serving:
    image: tensorflow/serving:latest
    volumes:
      - .cache/model:/model/1
    ports:
      - "9001:9000"
    command: "tensorflow_model_server --port=9000 --model_name=model --model_base_path=/model"
